import type { AccountDTO, EmployeeDTO, TransactionDTO, ServiceEndpoint } from '../types';

export const initialMockAccounts: AccountDTO[] = [
  {
    id: 1,
    accountNumber: 'APX-7749-0192',
    accountType: 'CHECKING',
    balance: 48520.50,
    employeeId: 101,
  },
  {
    id: 2,
    accountNumber: 'APX-9821-4431',
    accountType: 'SAVINGS',
    balance: 132450.00,
    employeeId: 101,
  },
  {
    id: 3,
    accountNumber: 'APX-3312-8820',
    accountType: 'INVESTMENT',
    balance: 750000.00,
    employeeId: 102,
  },
  {
    id: 4,
    accountNumber: 'APX-5519-2041',
    accountType: 'FIXED_DEPOSIT',
    balance: 50000.00,
    employeeId: 103,
  },
  {
    id: 5,
    accountNumber: 'APX-1120-6644',
    accountType: 'SAVINGS',
    balance: 18230.25,
    employeeId: 104,
  },
];

export const initialMockTransactions: TransactionDTO[] = [
  {
    id: 1001,
    accountId: 1,
    transactionType: 'DEPOSIT',
    amount: 5400.00,
    remarks: 'Monthly Executive Payroll Deposit',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 1002,
    accountId: 2,
    transactionType: 'DEPOSIT',
    amount: 15000.00,
    remarks: 'Quarterly Bonus Transfer',
    timestamp: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: 1003,
    accountId: 1,
    transactionType: 'WITHDRAWAL',
    amount: 750.00,
    remarks: 'Vendor Payment - Cloud Infrastructure',
    timestamp: new Date(Date.now() - 3600000 * 26).toISOString(),
  },
  {
    id: 1004,
    accountId: 3,
    transactionType: 'TRANSFER',
    amount: 25000.00,
    remarks: 'Portfolio Rebalancing Allocation',
    timestamp: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    id: 1005,
    accountId: 1,
    transactionType: 'WITHDRAWAL',
    amount: 120.00,
    remarks: 'ATM Cash Withdrawal',
    timestamp: new Date(Date.now() - 3600000 * 72).toISOString(),
  },
];

export const initialMockEmployees: EmployeeDTO[] = [
  {
    id: 101,
    employeeId: 'EMP-001',
    firstName: 'Alex',
    lastName: 'Vance',
    department: 'Engineering',
    designation: 'Staff Microservices Architect',
    salary: 145000.00,
    phone: '+1 (555) 234-8891',
    address: '450 Innovation Way, Suite 400',
  },
  {
    id: 102,
    employeeId: 'EMP-002',
    firstName: 'Sarah',
    lastName: 'Connor',
    department: 'Human Resources',
    designation: 'Senior HR Director',
    salary: 128000.00,
    phone: '+1 (555) 872-3312',
    address: '12 Cyberdyne Blvd, Sector 7',
  },
  {
    id: 103,
    employeeId: 'EMP-003',
    firstName: 'Marcus',
    lastName: 'Wright',
    department: 'Finance & Risk',
    designation: 'Senior Treasury Manager',
    salary: 135000.00,
    phone: '+1 (555) 661-9021',
    address: '88 Wall Street, Fl 14',
  },
  {
    id: 104,
    employeeId: 'EMP-004',
    firstName: 'Elena',
    lastName: 'Rostova',
    department: 'Compliance',
    designation: 'AML & Fraud Analyst',
    salary: 98000.00,
    phone: '+1 (555) 431-7711',
    address: '200 Federal Reserve Way',
  },
  {
    id: 105,
    employeeId: 'EMP-005',
    firstName: 'David',
    lastName: 'Kim',
    department: 'Operations',
    designation: 'Banking Operations Lead',
    salary: 110000.00,
    phone: '+1 (555) 902-1244',
    address: '777 Pacific Plaza',
  },
];

export const initialMockEndpoints: ServiceEndpoint[] = [
  {
    id: 'eureka',
    name: 'Eureka Discovery Server',
    port: 8761,
    targetUrl: 'http://localhost:8761',
    status: 'ONLINE',
    latencyMs: 14,
    description: 'Netflix Eureka Service Registry and Instance Discovery',
    category: 'core',
  },
  {
    id: 'gateway',
    name: 'Spring Cloud API Gateway',
    port: 8080,
    targetUrl: 'http://localhost:8080',
    status: 'ONLINE',
    latencyMs: 22,
    description: 'Reactive WebFlux Gateway & Reverse Proxy',
    category: 'gateway',
  },
  {
    id: 'banking',
    name: 'Banking Service',
    port: 8081,
    targetUrl: 'http://localhost:8081',
    status: 'ONLINE',
    latencyMs: 18,
    description: 'JWT Auth, Accounts, Transactions, and Employee records',
    category: 'service',
  },
  {
    id: 'payroll',
    name: 'Payroll Service',
    port: 8082,
    targetUrl: 'http://localhost:8082',
    status: 'ONLINE',
    latencyMs: 25,
    description: 'Payroll processing, salary dispatch, Kafka event listener',
    category: 'service',
  },
  {
    id: 'chatbot',
    name: 'AI Chatbot Assistant',
    port: 8083,
    targetUrl: 'http://localhost:8083',
    status: 'ONLINE',
    latencyMs: 45,
    description: 'AI-assisted customer & employee query resolution',
    category: 'ai',
  },
];

export const mockChatKnowledgeBase = [
  {
    keywords: ['balance', 'account balance', 'money', 'how much'],
    answer: "You can view your real-time account balances directly on the **Bank Accounts** tab or the **Executive Dashboard**. Total available liquidity across active accounts is currently displayed with live ledger sync.",
  },
  {
    keywords: ['transfer', 'send money', 'wire', 'deposit', 'withdraw'],
    answer: "To initiate a transfer or transaction, navigate to the **Transactions** page and click **'+ New Transaction'**. Select your source account, choose Deposit or Withdrawal, input the amount, and confirm. All records are validated instantly with your Spring Boot Banking backend.",
  },
  {
    keywords: ['payroll', 'salary', 'payslip', 'tax', 'deduction'],
    answer: "Payroll processing runs via the **Payroll-Service (Port 8082)**. Automatic direct deposit notifications are streamed via Apache Kafka when HR approves monthly disbursement batches.",
  },
  {
    keywords: ['eureka', 'microservice', 'architecture', 'port', 'status'],
    answer: "The backend is structured into 5 microservices:\n- **Eureka Server** (Port 8761)\n- **API Gateway** (Port 8080)\n- **Banking Service** (Port 8081)\n- **Payroll Service** (Port 8082)\n- **AI Chatbot Service** (Port 8083)\n\nCheck the **System Health** tab to inspect live connectivity status.",
  },
  {
    keywords: ['hr', 'create hr', 'employee', 'staff'],
    answer: "HR users can be created exclusively by **Administrators** via the **Employees** page using the **'Create HR User'** action. HR users have access to manage employee profiles and salary details.",
  },
];
